title: NLP Conference Deadlines for CAMeLers@NYUAD # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top NLP conference deadlines
author: Go Inoue

domain:
baseurl: "https://nizarhabash1.github.io/camel-deadlines"

twitter_username:
twitter_hashtag:
github_username: nizarhabash1
github_repo: camel-deadlines

markdown:
ga_id:
